//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_CEBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTATII
    {
        public short ID_CONSULTATIE { get; set; }
        public string DIAGNOSTIC { get; set; }
        public string SPITALIZARE { get; set; }
        public string RETETA { get; set; }
        public short ID_PROGRAMARE { get; set; }
    
        public virtual PROGRAMARI PROGRAMARI { get; set; }
    }
}
