//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_CEBD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONSULTATII> CONSULTATIIs { get; set; }
        public virtual DbSet<MEDICI> MEDICIs { get; set; }
        public virtual DbSet<PACIENTI> PACIENTIs { get; set; }
        public virtual DbSet<PROGRAMARI> PROGRAMARIs { get; set; }
        public virtual DbSet<SPECIALIZARI> SPECIALIZARIs { get; set; }
    }
}
