//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_CEBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTI()
        {
            this.PROGRAMARIs = new HashSet<PROGRAMARI>();
        }
    
        public short ID_PACIENT { get; set; }
        public string NUME { get; set; }
        public string PRENUME { get; set; }
        public string CNP { get; set; }
        public string ASIGURARE { get; set; }
        public string CARD_SANATATE { get; set; }
        public string ADRESA { get; set; }
        public string TELEFON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROGRAMARI> PROGRAMARIs { get; set; }
    }
}
