//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_CEBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMARI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROGRAMARI()
        {
            this.CONSULTATIIs = new HashSet<CONSULTATII>();
        }
    
        public short ID_PROGRAMARE { get; set; }
        public System.DateTime DATA { get; set; }
        public string ORA { get; set; }
        public string STATUS_PROGRAMARE { get; set; }
        public short ID_MEDIC { get; set; }
        public short ID_PACIENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTATII> CONSULTATIIs { get; set; }
        public virtual MEDICI MEDICI { get; set; }
        public virtual PACIENTI PACIENTI { get; set; }
    }
}
